config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]

  namespace :profile do
    resources :home, only: :index
    resources :recipes, param: :slug do
      get :edit_details, on: :member
      get :secret, on: :collection
      get :drafts, on: :collection

      scope module: :recipes do
        resources :ingredient_groups, only: %i[index new create edit update] do
          scope module: :ingredient_groups do
            resources :recipe_ingredients, only: %i[new index create update] do
              get :batch_edit, on: :collection
            end
          end
        end

        resources :nutrition_facts, only: %i[index edit update]
      end
    end

    root to: 'home#index'
  end

  resources :recipes, param: :slug
  resources :rooms do
    resources :messages
  end
  resource :password, only: %i[show edit update] do
    post :recover
  end

  root to: 'recipes#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  has_many :recipes, dependent: :restrict_with_exception
  has_many :tokens, dependent: :nullify
  has_many :password_recovery_tokens, -> { password_recovery }, class_name: 'Token', inverse_of: :user

  before_validation :downcase_email

  has_secure_password

  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_url
    else
      render 'new'
    end
  end

  def new; end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/new.slim
.row
  .col-md-6.offset-md-3
    h4 Регистрация
.row
  .col-md-6.offset-md-3.text-center
    = form_for :user, url: users_path, data: { turbo: false } do |f|
      = f.email_field :email, placeholder: t('.email'), class: 'form-control mb-1'
      = f.password_field :password, placeholder: t('.password'), class: 'form-control mb-1'
      = f.password_field :password_confirmation, placeholder: t('.password_confirmation'), class: 'form-control mb-1'
      .space-10
      = f.submit t('.registration'), class: 'btn btn-success'
    .space-10
    = link_to t('.sign_in'), new_session_path