config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]

  namespace :profile do
    resources :home, only: :index
    resources :recipes, param: :slug do
      get :edit_details, on: :member
      get :secret, on: :collection
      get :drafts, on: :collection

      scope module: :recipes do
        resources :ingredient_groups, only: %i[index new create edit update] do
          scope module: :ingredient_groups do
            resources :recipe_ingredients, only: %i[new index create update] do
              get :batch_edit, on: :collection
            end
          end
        end

        resources :nutrition_facts, only: %i[index edit update]
      end
    end

    root to: 'home#index'
  end

  resources :recipes, param: :slug
  resources :rooms do
    resources :messages
  end
  resource :password, only: %i[show edit update] do
    post :recover
  end

  root to: 'recipes#index'
end

app/views/shared/_navbar.slim
nav.navbar.navbar-expand-lg.bg-main role="navigation"
  .container
    .navbar-header
      a href=recipes_path
        = image_tag('icon.svg', alt: 'Бутерброд с колбасой', width: 220)

    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation"
      span.bi-list.text-white

    .collapse.navbar-collapse#navbarToggler
      ul.navbar-nav.mr-auto
        - if signed_in?
          li.nav-item
            = link_to t('.create_recipe'), new_profile_recipe_path, class: 'nav-link btn-link'
      ul.navbar-nav
        - if signed_in?
          li.nav-item
            = link_to t('profile.my_recipes'), profile_root_path, class: 'nav-link btn-link'
          li.nav-item
            = button_to t('.sign_out'), session_path, method: 'delete', form: { 'data-turbo': false }, class: 'nav-link btn-link'
        - else
          li.nav-item
            = link_to t('.sign_up'), new_user_path, class: 'nav-link btn-link'
          li.nav-item
            = link_to t('.sign_in'), new_session_path, class: 'nav-link btn-link'

app/views/shared/_recipe_ingredient.slim
tr
  td.col-sm-5 = recipe_ingredient.title
  td.col-sm-3 = recipe_ingredient.quantity
  td.col-sm-3 = I18n.t(recipe_ingredient.unit, scope: :units, count: recipe_ingredient.quantity)

app/views/shared/_recipe_ingredients.slim
table.table.table-bordered.table-striped
  - ingredient_group.recipe_ingredients.each do |recipe_ingredient|
    = render partial: 'shared/recipe_ingredient', locals: { recipe_ingredient: recipe_ingredient }