config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]

  namespace :profile do
    resources :home, only: :index
    resources :recipes, param: :slug do
      get :edit_details, on: :member
      get :secret, on: :collection
      get :drafts, on: :collection

      scope module: :recipes do
        resources :ingredient_groups, only: %i[index new create edit update] do
          scope module: :ingredient_groups do
            resources :recipe_ingredients, only: %i[new index create update] do
              get :batch_edit, on: :collection
            end
          end
        end

        resources :nutrition_facts, only: %i[index edit update]
      end
    end

    root to: 'home#index'
  end

  resources :recipes, param: :slug
  resources :rooms do
    resources :messages
  end
  resource :password, only: %i[show edit update] do
    post :recover
  end

  root to: 'recipes#index'
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  include ImageUploader::Attachment(:image)
  include AASM

  belongs_to :user
  has_many :ingredient_groups, dependent: :destroy
  has_many :recipe_ingredients, through: :ingredient_groups
  has_many :ingredients, through: :recipe_ingredients

  validates :title, presence: true
  validates :body, presence: true

  before_create :generate_slug
  after_commit :generate_image_derivatives

  aasm column: :state do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :to_draft do
      transitions from: :published, to: :draft
    end
  end

  scope :for_public, -> { where(secret: false).published.order(created_at: :desc) }
  scope :secret, -> { where(secret: true) }

  def nutrition_fact
    return if recipe_ingredients.blank?
    return unless can_calculate_nutrition_fact?

    @nutrition_fact ||= begin
      total_weight_g = recipe_ingredients.sum(&:weight_g)

      return if total_weight_g.zero?

      recipe_ingredients.sum(&:nutrition_fact).scale(BigDecimal('100') / total_weight_g)
    end
  end

  def to_param
    slug
  end

  private

  def can_calculate_nutrition_fact?
    recipe_ingredients.detect { |recipe_ingredient| recipe_ingredient.nutrition_fact.blank? }.nil?
  end

  def generate_image_derivatives
    return if image.blank?

    image_derivatives!
  end

  def generate_slug
    next_id = Recipe.connection.select_value("SELECT NEXTVAL('recipes_id_seq')")

    self.slug ||= [next_id, I18n.transliterate(title.strip).downcase.tr(' ', '-')].join('-')
  end
end

app/controllers/profile/recipes/application_controller.rb
# frozen_string_literal: true

module Profile
  module Recipes
    class ApplicationController < Profile::ApplicationController
      helper_method :current_recipe

      def current_recipe
        @current_recipe ||= current_user.recipes.find_by!(slug: params[:recipe_slug])
      end
    end
  end
end

app/controllers/profile/recipes/ingredient_groups/application_controller.rb
# frozen_string_literal: true

module Profile
  module Recipes
    module IngredientGroups
      class ApplicationController < Profile::Recipes::ApplicationController
        helper_method :current_ingredient_group

        def current_ingredient_group
          @current_ingredient_group ||= current_recipe.ingredient_groups.find(params[:ingredient_group_id])
        end
      end
    end
  end
end

app/controllers/profile/recipes/ingredient_groups/recipe_ingredients_controller.rb
# frozen_string_literal: true

module Profile
  module Recipes
    module IngredientGroups
      class RecipeIngredientsController < Profile::Recipes::IngredientGroups::ApplicationController
        def new
          @recipe_ingredient = current_ingredient_group.recipe_ingredients.new
        end

        # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
        def create
          recipe_ingredient = current_ingredient_group.recipe_ingredients.new(recipe_ingredient_params)
          recipe_ingredient.save

          respond_to do |format|
            format.html { redirect_to profile_recipe_ingredient_groups_path(current_recipe) }
            format.turbo_stream do
              render(
                turbo_stream: turbo_stream.update(
                  "ingredient_group_#{current_ingredient_group.id}_list",
                  partial: 'shared/recipe_ingredients',
                  locals: { ingredient_group: current_ingredient_group }
                )
              )
            end
          end
        end
        # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

        def batch_edit
          @recipe_ingredients = current_recipe.recipe_ingredients
        end

        def update; end

        private

        def recipe_ingredient_params
          params.require(:recipe_ingredient).permit(:title, :quantity, :unit)
        end
      end
    end
  end
end

app/controllers/profile/recipes/ingredient_groups_controller.rb
# frozen_string_literal: true

module Profile
  module Recipes
    class IngredientGroupsController < Profile::Recipes::ApplicationController
      def index
        @recipe_ingredient = RecipeIngredient.new
        @ingredient_group = IngredientGroup.new
      end

      def new
        @ingredient_group = current_recipe.ingredient_groups.new
      end

      # rubocop:disable Metrics/MethodLength
      def create
        @ingredient_group = current_recipe.ingredient_groups.new(ingredient_group_params)
        @ingredient_group.save

        respond_to do |format|
          format.turbo_stream do
            render(
              turbo_stream: turbo_stream.append(
                "recipe_#{current_recipe.id}",
                partial: 'profile/recipes/ingredient_groups/ingredient_group',
                locals: { ingredient_group: @ingredient_group }
              )
            )
          end
        end
      end
      # rubocop:enable Metrics/MethodLength

      def edit
        @ingredient_group = current_recipe.ingredient_groups.find(params[:id])
      end

      # rubocop:disable Metrics/MethodLength
      def update
        @ingredient_group = current_recipe.ingredient_groups.find(params[:id])
        @ingredient_group.update(ingredient_group_params)

        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace(
              "edit_ingredient_group_#{@ingredient_group.id}",
              partial: 'profile/recipes/ingredient_groups/update_title',
              locals: { ingredient_group: @ingredient_group }
            )
          end
        end
      end
      # rubocop:enable Metrics/MethodLength

      private

      def ingredient_group_params
        params.require(:ingredient_group).permit(:title)
      end
    end
  end
end

app/controllers/profile/recipes/nutrition_facts_controller.rb
# frozen_string_literal: true

module Profile
  module Recipes
    class NutritionFactsController < Profile::Recipes::ApplicationController
      def index; end

      def edit
        @recipe_ingredient = current_recipe.recipe_ingredients.find(params[:id])
      end

      def update
        @recipe_ingredient = current_recipe.recipe_ingredients.find(params[:id])
        @recipe_ingredient.update(recipe_ingredient_params)

        render turbo_stream: turbo_stream.replace(
          "edit_recipe_ingredient_#{@recipe_ingredient.id}",
          partial: 'profile/recipes/nutrition_facts/recipe_ingredient_row',
          locals: { recipe_ingredient: @recipe_ingredient }
        )
      end

      private

      def recipe_ingredient_params
        params.require(:recipe_ingredient).permit(:protein_g, :fat_g, :carbohydrates_g, :unit_g)
      end
    end
  end
end

app/controllers/profile/recipes_controller.rb
# frozen_string_literal: true

module Profile
  class RecipesController < Profile::ApplicationController
    def new
      @recipe = Recipe.new
    end

    def create
      result = ::Recipes::Create.call(user: current_user, recipe_params: recipe_params)

      if result.success?
        redirect_to profile_recipe_ingredient_groups_path(result.recipe)
      else
        @recipe = result.recipe
        render :new
      end
    end

    def edit
      @recipe = current_user.recipes.find_by!(slug: params[:slug])
    end

    def edit_details
      @recipe = current_user.recipes.find_by!(slug: params[:slug])
    end

    def update
      @recipe = current_user.recipes.find_by!(slug: params[:slug])
      if @recipe.update(recipe_params)
        @recipe.publish! unless @recipe.published?

        redirect_to profile_recipe_path(@recipe)
      else
        render 'edit'
      end
    end

    def show
      @recipe = current_user.recipes.find_by!(slug: params[:slug])
    end

    def secret
      @recipes = Recipe.published.secret.page(params[:page]).per(16)
    end

    def drafts
      @recipes = Recipe.draft.page(params[:page]).per(16)
    end

    private

    def recipe_params
      params.require(:recipe).permit(:title, :body, :image, :description, :secret)
    end
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    @recipes = Recipe.for_public.page(params[:page]).per(16)
  end

  def show
    @recipe = Recipe.find_by!(slug: params[:slug])
  end
end

app/helpers/profile/recipes/recipe_ingredients_helper.rb
# frozen_string_literal: true

module Profile
  module Recipes
    module RecipeIngredientsHelper
      def units
        Unit::UNITS.index_by do |unit|
          I18n.t(unit, scope: :units, count: 0)
        end
      end
    end
  end
end

app/helpers/profile/recipes_helper.rb
# frozen_string_literal: true

module Profile
  module RecipesHelper
    def nutrition_facts_showable?(*)
      false
    end
  end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
  def can_edit_recipe?(recipe, user)
    recipe.user_id == user&.id
  end
end

app/views/shared/recipes/_nutrition_facts.slim
.nutrition-facts
  - if recipe.nutrition_fact.present?
    table.w-100.text-center.table-md
      tr
        td.w-25.border-right.border-main
          b = t('nutrition_facts.calories')
          br
          i = t('nutrition_facts.per_100_g')
          - if can_edit_recipe?(recipe, current_user)
            | &nbsp;
            = link_to profile_recipe_nutrition_facts_path(recipe) do
              span.bi-pencil.mx-1
        td.w-25.border-right.border-main
          b = t('nutrition_facts.protein')
        td.w-25.border-right.border-main
          b = t('nutrition_facts.fat')
        td.w-25
          b = t('nutrition_facts.carbs')
      tr.border-top.border-main
        td.w-25.border-right.border-main
          b = t('nutrition_facts.kkal', count: recipe.nutrition_fact.calories.round)
        td.w-25.border-right.border-main
          = t('nutrition_facts.g', count: recipe.nutrition_fact.protein_g.round(2))
        td.w-25.border-right.border-main
          = t('nutrition_facts.g', count: recipe.nutrition_fact.fat_g.round(2))
        td.w-25
          = t('nutrition_facts.g', count: recipe.nutrition_fact.carbohydrates_g.round(2))
  - else
    .mx-2
      i
        = t('.no_nutrition_facts_yet')
        - if can_edit_recipe?(recipe, current_user)
          | &nbsp;
          = link_to "(#{t('.calculate')})", profile_recipe_nutrition_facts_path(recipe), class: 'small text-muted'

app/views/shared/recipes/_recipe.slim
.row
  .col-md-6
    img src=(recipe.image_url(:large) || asset_path('recipe_placeholder.jpg')) class='w-100 card-img'

  .col-md-6
    .row
      .col-md-12
        h1.text-capitalize
          = recipe.title
          - if can_edit_recipe?(recipe, current_user)
            = link_to I18n.t('edit'), edit_profile_recipe_path(recipe), class: 'btn btn-link btn-sm small text-muted'
    .row
      .col-md-12
        = render partial: 'shared/recipes/nutrition_facts', locals: { recipe: recipe }
.space-20
.row
  .col-md-4
    h3
      = Recipe.human_attribute_name(:ingredients)
    - recipe.ingredient_groups.each do |ingredient_group|
      - if ingredient_group.title
        h5 = ingredient_group.title
      table.table.table-sm.table-striped.table-borderless.w-100
        - ingredient_group.recipe_ingredients.each do |recipe_ingredient|
          tr
            td.text-capitalize
              = recipe_ingredient.ingredient_title
            td.text-end
              span.visible
                = recipe_ingredient.metric_quantity
              span.invisible
                = recipe_ingredient.imperial_quantity

  .col-md-8
    h3 = Recipe.human_attribute_name(:body)
    = simple_format(recipe.body)

app/views/shared/recipes/_small_card.slim
.recipe-card
  a href=recipe_path(recipe)
    .card
      img.card-img src=recipe.image_url(:thumb) style="display:block; width:100%; min-height:200px; background:url(#{asset_path('recipe_placeholder.jpg')}); background-size: 100%"
      .card-img-overlay.text-truncate.text-white
        = recipe.title